# Generated by Django 4.2.7 on 2025-10-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentnotification',
            name='recipient_type',
            field=models.CharField(choices=[('all', 'Все пользователи'), ('ssk', 'ССК'), ('iko', 'ИКО'), ('foreman', 'Прораб')], max_length=10, verbose_name='Тип получателей'),
        ),
    ]
