# Generated by Django 4.2.7 on 2025-10-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sentnotification_recipient_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceticket',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='user_id',
            field=models.CharField(default='', max_length=100, verbose_name='ID пользователя'),
            preserve_default=False,
        ),
    ]
