# Generated by Django 4.2.7 on 2025-10-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_maintenanceticket_email_maintenanceticket_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='link',
        ),
        migrations.AddField(
            model_name='memo',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя файла'),
        ),
        migrations.AddField(
            model_name='memo',
            name='file_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Размер файла (байты)'),
        ),
        migrations.AddField(
            model_name='memo',
            name='file_url',
            field=models.URLField(blank=True, max_length=5000, null=True, verbose_name='Ссылка на файл'),
        ),
        migrations.AddField(
            model_name='memo',
            name='object_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID объекта'),
        ),
        migrations.AddField(
            model_name='memo',
            name='object_name',
            field=models.CharField(blank=True, max_length=2049, null=True, verbose_name='Название объекта'),
        ),
    ]
